package models;
// Generated 03-mar-2021 20:03:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {


     private BigDecimal idcoche;
     private String marca;
     private String modelo;
     private String conductor;
     private String imagen;

    public Coches() {
    }

	
    public Coches(BigDecimal idcoche) {
        this.idcoche = idcoche;
    }
    public Coches(BigDecimal idcoche, String marca, String modelo, String conductor, String imagen) {
       this.idcoche = idcoche;
       this.marca = marca;
       this.modelo = modelo;
       this.conductor = conductor;
       this.imagen = imagen;
    }
   
    public BigDecimal getIdcoche() {
        return this.idcoche;
    }
    
    public void setIdcoche(BigDecimal idcoche) {
        this.idcoche = idcoche;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getConductor() {
        return this.conductor;
    }
    
    public void setConductor(String conductor) {
        this.conductor = conductor;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


